[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "^1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/tuvistavie/securerandom"

[[constraint]]
  name = "github.com/wavefronthq/go-metrics-wavefront"
  branch = "laullon/v1"
